### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by bastibuck** [kozi/contao-simpletipp#4]
Hallo kozi,

ich kriege die neuste Version einfach nicht zum laufen... 
0.3.1 lief, aber hat die Tipps nicht mit der OpenLigeDB vergleichen und die Punkte vergeben. Jetzt habe ich auf die neuste Version (einmal die von GitHub und einmal die aus dem ER) upgedatet - ohne Erfolg.

Jetzt kriege ich immer wieder diese Fehlermeldung:

```
Fatal error: Uncaught exception Exception with message Too few arguments to build the query string thrown in D:\xampp\htdocs\ktv\system\modules\core\library\Contao\Database\Statement.php on line 316

#0 D:\xampp\htdocs\ktv\system\modules\core\library\Contao\Database\Statement.php(253): Contao\Database\Statement->replaceWildcards(Array)
#1 D:\xampp\htdocs\ktv\system\modules\simpletipp\modules\SimpletippMatches.php(105): Contao\Database\Statement->execute(Array)
#2 D:\xampp\htdocs\ktv\system\modules\simpletipp\modules\SimpletippMatches.php(71): SimpletippMatches->getMatches()
#3 D:\xampp\htdocs\ktv\system\modules\core\modules\Module.php(163): SimpletippMatches->compile()
#4 D:\xampp\htdocs\ktv\system\modules\simpletipp\modules\SimpletippMatches.php(50): Contao\Module->generate()
#5 D:\xampp\htdocs\ktv\system\modules\core\elements\ContentModule.php(63): SimpletippMatches->generate()
#6 D:\xampp\htdocs\ktv\system\modules\core\library\Contao\Controller.php(468): Contao\ContentModule->generate()
#7 D:\xampp\htdocs\ktv\system\modules\core\modules\ModuleArticle.php(196): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#8 D:\xampp\htdocs\ktv\system\modules\core\modules\Module.php(163): Contao\ModuleArticle->compile()
#9 D:\xampp\htdocs\ktv\system\modules\core\modules\ModuleArticle.php(59): Contao\Module->generate()
#10 D:\xampp\htdocs\ktv\system\modules\core\library\Contao\Controller.php(404): Contao\ModuleArticle->generate(false)
#11 D:\xampp\htdocs\ktv\system\modules\core\library\Contao\Controller.php(268): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#12 D:\xampp\htdocs\ktv\system\modules\core\pages\PageRegular.php(138): Contao\Controller::getFrontendModule('0', 'main')
#13 D:\xampp\htdocs\ktv\index.php(263): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#14 D:\xampp\htdocs\ktv\index.php(447): Index->run()
#15 {main}
```

Ich vermute, dass es daran liegt, dass ich in dem Modul nicht mehr die Tipprunde auswählen kann, die ausgegeben werden soll. 
Oder mache ich irgendwelche Einstellungen falsch? Unter 0.3.1 lief es so. Der einzige Fehler war wie gesagt, dass die Endergebnisse nicht aus OpenLigaDB übernommen und die Punkte nicht verteilt wurden.

Läuft die Erweiterung bei dir inklusive Auswertung etc? Könntest du mir kurz erklären, wie ich es einrichten muss?
ich würde mich anschließend gerne bereit erklären, die Anleitung deutlich ausführlicher zu beschreiben und dir zur Verfügung zu stellen, so dass mehr Anwender deine tolle Erweiterung nutzen können.

Danke,
Sebi

PS: Du kannst mich auch gerne mal per Email (siehe mein Profil) kontaktieren, würde wie gesagt gerne bei der Anleitung helfen. Scheint noch mehr Leute zu geben, die das nicht zum laufen kriegen.

**Comment by kozi** [comment]
Die Erweiterung hat sich mittlerweile start verändert. Bitte die akuellste Version installieren und dann bei Problem hier ein neues Ticket erstellen!
